import type { Metadata } from 'next';
import { Open_Sans, Poppins } from 'next/font/google';
import '../../globals.css';
import AdminNavbar from '@/components/AdminNavbar/AdminNavbar';
import AdminASide from '@/components/AdminAside/AdminAside';

const openSans = Open_Sans({
   subsets: ['latin'],
   weight: ['400', '700'],
   variable: '--font-open-sans',
   display: 'swap',
});

const poppins = Poppins({
   subsets: ['latin'],
   weight: ['400', '700'],
   variable: '--font-poppins',
   display: 'swap',
});

export const metadata: Metadata = {
   title: 'Hunty',
   description: 'Generated by Hunty',
};

export default async function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className={`${poppins.variable} ${openSans.variable}`}>
         <body
            className={`antialiased overscroll-none font-(family-name:--font-poppins)`}
         >
            <AdminNavbar />
            <div className="flex w-screen">
               <aside className="bg-white w-60 2xl:w-90 shadow-md/50 z-1">
                  <AdminASide />
               </aside>
               <main className="bg-gray-100 w-full p-4 px-8">{children}</main>
            </div>
         </body>
      </html>
   );
}
