import type { Metadata } from 'next';
import { Open_Sans, Poppins } from 'next/font/google';
import './globals.css';

const openSans = Open_Sans({
   subsets: ['latin'],
   weight: ['400', '700'],
   variable: '--font-open-sans',
   display: 'swap',
});

const poppins = Poppins({
   subsets: ['latin'],
   weight: ['400', '700'],
   variable: '--font-poppins',
   display: 'swap',
});

export const metadata: Metadata = {
   title: 'Hunty',
   description: 'Generated by Hunty',
};

export default async function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className={`${poppins.variable} ${openSans.variable}`}>
         <body
            className={`antialiased overscroll-none font-(family-name:--font-poppins)`}
         >
            {children}
         </body>
      </html>
   );
}
